# Generated by Django 4.2 on 2023-04-16 00:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_publishedmanager"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PublishedManager",
        ),
    ]
